export interface AppForm {
    name: string,
    email: string,
    address: string,
    city: string,
    state: string,
    phone: Number,
    companyName: string,
    teamBackground: string,
    companyProducts: string,
    problem: string,
    solution: string,
    proposition: string,
    competitors: string,
    revenue: string,
    marketSize: string,
    marketPlan: string,
    options: string,
    proposal: string,
}
